import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/SideBar/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DO IT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden max-h-screen`}
      >
        <Toaster />
        <ReduxProvider >
          <div className=" flex flex-col">
            <div className="h-[40px]">
            <Navbar />
            </div>
            <div className="p-4 h-[calc(100vh-40px)] flex">
              <div className="h-full ">
                <Sidebar />
              </div>
              <div className="h-full">{children}</div>

            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
