import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReduxProvider from "./ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/SideBar/SideBar";
import '../index.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DO IT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className=" h-screen">
        <Toaster />
        <ReduxProvider >
          <div className=" flex flex-col w-screen">
            <div className="h-[40px] w-full">
            <Navbar />
            </div>
            <div className="p-2 h-[calc(100vh-40px)] flex w-full">
                <Sidebar />
              <div className="h-full w-full">{children}</div>
            </div>
          </div>
        </ReduxProvider>
      </div>
  );
}
